export const CODE = {
	ALL: Symbol('ALL'),
	ERR_STATUS: Symbol('ERR_STATUS'),
	NOT_ALLOWED: Symbol('NOT_ALLOWED'),
	TARGET_DISTANCE_ZERO: Symbol('TARGET_DISTANCE_ZERO'),

	ERR_UNKNOWN_ORDER: Symbol('ERR_UNKNOWN_ORDER'),
	ERR_OBSTACLE: Symbol('ERR_OBSTACLE'),
	ERR_NOT_IN_RANGE: Symbol('ERR_NOT_IN_RANGE'),
	ERR_MODULE_MISSING: Symbol('ERR_MODULE_MISSING'),
	ERR_BIG_DIFF_HEIGHT: Symbol('ERR_BIG_DIFF_HEIGHT'),
	ERR_NOT_ENOUGH_SPACE: Symbol('ERR_NOT_ENOUGH_SPACE'),
	ERR_NOT_ENOUGH_ENERGY: Symbol('ERR_NOT_ENOUGH_ENERGY'),
	ERR_TARGET_NOT_FOUND: Symbol('ERR_TARGET_NOT_FOUND'),
	ERR_RESOURCE_NOT_FOUND: Symbol('ERR_RESOURCE_NOT_FOUND'),
	ERR_CARGO_IS_OVERFLOWING: Symbol('ERR_CARGO_IS_OVERFLOWING'),
};
